use std::fmt::format;
use std::net::TcpListener;
use actix_web::{HttpResponse, web};
use actix_web::web::Data;
use sqlx::{Connection,Executor, PgConnection, PgPool};
use sqlx::types::Uuid;
use once_cell::sync::Lazy;
use ZeroToProd::telemetry::{get_subscriber,init_subscriber};
use ZeroToProd::configuration::{get_configuration,DatabaseSettings};
use ZeroToProd::email_client::EmailClient;
use ZeroToProd::startup::run;
