application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "mohanvenkatesh"
  password: "Msvmsd183!"
  database_name: "mohan"
email_client:
  base_url: "localhost"
  sender_email: "mohan_venkatesh@heartcore.co.jp"
  authorization_token: "my-secret-token"
